name: Daily Test

on:
  schedule:
    - cron: '13 13 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'ubuntu-20.04'
          - 'ubuntu-latest'
        hugo-version:
          - 'latest'
          - '0.61.0'
        extended:
          - true
          - false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Hugo
        uses: ./
        with:
          hugo-version: ${{ matrix.hugo-version }}
          extended: ${{ matrix.extended }}

      - name: Run hugo version
        run: echo "::set-output name=hugo_version::$(hugo version)"
        id: hugo_version

      - name: '${{ steps.hugo_version.outputs.hugo_version }}'
        run: echo '${{ steps.hugo_version.outputs.hugo_version }}'
